name: SNMP::Effective
version_from: lib/SNMP/Effective.pm
abstract: Effective SNMP collector
author: Jan Henning Thorsen
license: perl
installdirs: site
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
requires:
    SNMP: 0
    Time::HiRes: 0
    Tie::Array: 0
build_requires:
    Test::More: 0
    Test::Perl::Critic: 0
    Test::Pod: 1.14
    Test::Pod::Coverage: 1.04
provides:
    SNMP::Effective:
        file: lib/SNMP/Effective.pm
    SNMP::Effective::Dispatch:
        file: lib/SNMP/Effective/Dispatch.pm
    SNMP::Effective::Host:
        file: lib/SNMP/Effective/Host.pm
    SNMP::Effective::HostList:
        file: lib/SNMP/Effective/HostList.pm
    SNMP::Effective::Logger:
        file: lib/SNMP/Effective/Logger.pm
    SNMP::Effective::VarList:
        file: lib/SNMP/Effective/VarList.pm

resources:
    homepage: http://trac.flodhest.net/pm/wiki/SNMP-Effective
    repository: http://trac.flodhest.net/pm/browser/SNMP-Effective
    bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=SNMP-Effective

